### ISSUE TITLE
Archive post not fetch properly

### ISSUE THREAD

**Issue by mahbub095** [pluginever/wp-content-pilot#101]
-Content does not fetch properly[https://prnt.sc/ymobku](https://prnt.sc/ymobku)
-Check content [source. ](https://www.bbc.com/news/topics/cx1m7zg01xyt/united-states)

**Comment by sudipto-me** [comment]
It will not possible. Because this type of source which based on the archive is created by just using javascript. So when curl is run for getting the contents from the source it just gets the javascript code. That is the reason, archive posts are not fetched properly. I also checked with the wp automatic for these options. It also has the same issue.
