### ISSUE TITLE
Impossible create a compaign

### ISSUE THREAD

**Issue by RasBaba** [pluginever/wp-content-pilot#4]
i'm following your istruction to do an article compaign, but when i try a test i have always this answer:"Could not retrieve any valid links".

**Comment by sultann** [comment]
@RasBaba 
The message "Could not retrieve any valid links" means the keyword you are targeting the "WP Content Pilot" could not find any good articles links. You can try multiple keywords in the same  campaign so please try different combination of keywords.

**Comment by RasBaba** [comment]
@sultann 
Every combination i try, the answer is always the same. 
I tried with the food, music and the last one I tried using the following keywords: soccer, football, juventus, manchester, real madrid, champions league, roma, barcelona.... and the result is always "Could not retrieve any valid links."

**Comment by sultann** [comment]
@RasBaba 
Most of the keyword you are trying is a single word and WP Content Pilot use Yahoo search. If you try with those keywords you will see the first page on google does not shows any article links instead of the site home page. Our current setup is when it could not get any links from the first page then the campaign get failed. I will release a new version so, it will look for the next page of the search result when it could not find any article links on the first page.
By this time you can elaborate the keywords so it shows article links on yahoo. Like "manchester football matches 2018"

Here is a test that I did https://d.pr/v/JYM0CP

**Comment by RasBaba** [comment]
Thank you man, but I don't know, it does not work either way, you can see the screenshot.
 I will try to uninstall the plugin and then install it again. 
![screenshot 2018-03-13 alle 18 43 16](https://user-images.githubusercontent.com/28945357/37359851-f1791bc0-26ee-11e8-8560-e75d433b6a4d.png)

**Comment by sultann** [comment]
@RasBaba , I just released an update of the plugin. You can try and if it works now.

**Comment by RasBaba** [comment]
Thanks, it's a surprise, really kindly, i'll try it soon and i'll tell you the response.

Thank you very much

**Comment by sultann** [comment]
@RasBaba Can you share a temporary user/pass to check the issue? use suppor@pluginever.com

**Comment by sultann** [comment]
@RasBaba  
We have worked a lot on the plugin to make it workable.
Can you please try install a fresh version of the plugin.
or try a demo from here http://wpcp.pluginever.com/wp-admin/
